name: brian2-2.2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - brian2==2.2.1
  - matplotlib[version='>=3.5.3']
  - numpy[version='>=1.19']
  - pandas[version='>=1.3.5']
  - python[version='>=3.6.8,<3.8.0']
  - scikit-learn[version='>=1.0.2']
  - scipy[version='>=1.7.3']
platforms:
  - osx-64
  - linux-64
  - win-64
