name: brian2-2.2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - brian2==2.2.1
  - matplotlib==3.0.2
  - numpy==1.15.4
  - pandas==0.24.1
  - python[version='>=3.6.8,<3.7.0']
  - scikit-learn==0.19.2
  - scipy==1.2.0
platforms:
  - osx-64
  - linux-64
