name: Linux
on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #   pull_request:

env:
  CHAT_NUM_TRIAL: 10
  CHAT_NUM_MF: 78
  CHAT_NUM_GRC: 1024
  CHAT_NUM_GOC: 7
  CHAT_SEED_TRIAL: 451

jobs:
  build:
    name: Build (py${{ matrix.python-version }}, ${{ matrix.os }})
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]
        include:
          - lock_os: linux-64
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        timeout-minutes: 10
        with:
          auto-update-conda: false
          activate-environment: brian2-2.2.1
          environment-file: lock_files/conda-${{ matrix.lock_os }}.lock

      - name: Run simulation
        run: |
          conda activate brian2-2.2.1
          python run_simulation.py

          # calculate simulation output hashes
          shasum -a 256 *.npy > ./.github/test/test-${{ env.CHAT_NUM_TRIAL }}trials-${{ matrix.lock_os }}.sha256

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update file hashes on ${{ matrix.lock_os }}
          title: update file hashes on ${{ matrix.lock_os }}
          body: |
            Updates simulation file hashes, if this is unexpected check for simulation drift

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: test-sim
          branch: test-${{ matrix.lock_os }}
